ALTER TABLE `games` ADD `purgeScheduledAt` timestamp NULL;
ALTER TABLE `games` ADD `temporarySafeObject` varchar(255) NULL;
ALTER TABLE `games` ADD `temporarySafeObjectExpiresAt` timestamp NULL;
ALTER TABLE `games` ADD `deletedAt` timestamp NULL;
ALTER TABLE `game_players` ADD `reservedPoints` int DEFAULT 0;
ALTER TABLE `bounties` ADD `expiresAt` timestamp NULL;
UPDATE `bounties` SET `expiresAt` = DATE_ADD(`createdAt`, INTERVAL 6 HOUR) WHERE `expiresAt` IS NULL;
ALTER TABLE `player_power_ups` ADD `activatedRound` int NULL;
ALTER TABLE `player_power_ups` ADD `pausedAt` timestamp NULL;
ALTER TABLE `player_power_ups` ADD `remainingDurationSeconds` int NULL;
ALTER TABLE `player_power_ups` ADD `lockedForDuelId` int NULL;
ALTER TABLE `eliminations` ADD `basePointsAtSubmission` int NULL;
ALTER TABLE `eliminations` ADD `bountyPointsAtSubmission` int DEFAULT 0;
ALTER TABLE `duels` MODIFY `status` enum('pending','awaiting_opponent_stake','awaiting_result','pending_review','resolved','rejected') NOT NULL DEFAULT 'awaiting_opponent_stake';
UPDATE `duels` SET `status` = 'rejected' WHERE `status` = 'pending';
ALTER TABLE `duels` MODIFY `status` enum('awaiting_opponent_stake','awaiting_result','pending_review','resolved','rejected') NOT NULL DEFAULT 'awaiting_opponent_stake';
ALTER TABLE `duels` ADD `proposedWinnerId` int NULL;
ALTER TABLE `duels` ADD `challengerStakeId` int NULL;
ALTER TABLE `duels` ADD `opponentStakeId` int NULL;
ALTER TABLE `duels` ADD `stakeDeadline` timestamp NULL;
ALTER TABLE `duels` ADD `evidenceUrl` text NULL;
ALTER TABLE `duels` ADD `witnessName` varchar(255) NULL;
ALTER TABLE `duels` ADD `submissionNotes` text NULL;
ALTER TABLE `duels` ADD `submittedAt` timestamp NULL;
ALTER TABLE `duels` ADD `reviewedBy` int NULL;
UPDATE `power_ups` SET `name` = 'Doppelganger' WHERE `name` = 'Doppleganger';
UPDATE `power_ups` SET `name` = 'Care Package' WHERE `name` = 'Care package';
UPDATE `power_ups` SET `cost` = 100, `duration` = NULL, `usageFeeCents` = 0 WHERE `name` = 'Bounty';
UPDATE `power_ups` SET `duration` = NULL, `usageFeeCents` = 0 WHERE `name` = 'Raise the Stakes';
UPDATE `power_ups` SET `duration` = NULL WHERE `name` IN ('Recon','Strip Search','Lucky Charm','Mirror, Mirror');
UPDATE `power_ups` SET `duration` = 240 WHERE `name` = 'Blacklist';
UPDATE `power_ups` SET `duration` = 360 WHERE `name` = 'Vendetta';
UPDATE `power_ups` SET `duration` = 240 WHERE `name` = 'Bodyguard';
UPDATE `power_ups` SET `duration` = 40 WHERE `name` = 'Open Season';
